apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - rbac.yaml
  - deployment.yaml
  # Copy secret.example.yaml to secret.yaml, fill real values and uncomment next line.
  # - secret.yaml
