apiVersion: v1
kind: Secret
metadata:
  name: devops-bot-secret
  namespace: devops-bot
type: Opaque
stringData:
  TELEGRAM_TOKEN: "PASTE_TELEGRAM_BOT_TOKEN_HERE"
  AI_API_KEY: "PASTE_AI_API_KEY_HERE"
